BaoThanh/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTDD_BaoThanh.Models;
using System.Data.Entity;

namespace DTDD_BaoThanh.Areas.Admin.Controllers
{
    public class CategoriesController : Controller
    {

        private MobileShopEntities db = new MobileShopEntities();


        // GET: Admin/Categories
        public ActionResult Index()
        {
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Dashboard");
            }
            return View();
        }

        public ActionResult GetCategories()
        {
            var CategoriesList = db.tbl_Categories.Select(m => new
            {
                Id = m.Id,
                Name = m.Name

            }).ToList();
            return Json(CategoriesList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCategoryByID(int id)
        {
            var item = db.tbl_Categories.Select(m => new
            {
                Id = m.Id,
                Name = m.Name

            }).Where(m=>m.Id == id);

            return Json(item, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Create([Bind(Include ="Id,Name")] tbl_Categories NewCategory)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Categories.Add(NewCategory);
                db.SaveChanges();
            }

            return Json(NewCategory, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Edit(tbl_Categories Category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Category).State = EntityState.Modified;
                db.SaveChanges();

            }
            return Json(Category, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete (int id)
        {
            var category = db.tbl_Categories.Find(id);
            if(category != null)
            {
                db.tbl_Categories.Remove(category);
                db.SaveChanges();
            }
            return Json(category, JsonRequestBehavior.AllowGet);
        }

    }
}

BaoThanh/Areas/Admin/Views/Categories/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Danh mục Sản Phẩm
        <button type="button" onclick="return BtnCreateNewOnClick()" id="btnCreateNew" class="btn btn-primary" data-toggle="modal" data-target="#categoryModal" style="float:right;">
            Create New
        </button>
    </div>
    <div class="card-body">
        @*table dùng để hiển thị danh sách*@
        <div class="table-responsive">
            <table id="listCategory" class="table">
                <thead>
                    <tr>
                        <th><label>Id</label></th>
                        <th><label>Name</label></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>


        @*modal dùng để hiển thị form Create và Update*@
        <div class="modal fade" id="categoryModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title"><label id="title"></label></h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="hidden" class="form-control" id="Id" />
                                    <label>Name</label>
                                    <input type="text" id="Name" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="btnClose" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" id="btnSave" onclick="return BtnSaveOnClick()" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@*hàm xử lý Ajax ngay trong trang Index*@

@section Scripts{

    <script type="text/javascript">

        $(document).ready(function () {
            GetCategories();
        })

        var isUpdatable = false;

        function GetCategories() {
            var GetCategoriesUrl = '@Url.Action("GetCategories","Categories")';
            $.getJSON(GetCategoriesUrl, function (data) {
                if (data != null) {
                    var rows = '';
                    $.each(data, function (i, item) {
                        rows += "<tr>"
                        rows += "<td>" + item.Id + "</td>"
                        rows += "<td>" + item.Name + "</td>"
                        rows += "<td><button type='button' id='btnEdit' class='btn btn-default' onclick='return GetCategoryByID(" + item.Id + ")'>Edit</button> <button type='button' id='btnDelete' class='btn btn-danger' onclick='return Delete(" + item.Id + ")'>Delete</button></td>"
                        rows += "</tr>";
                        $("#listCategory tbody").html(rows);
                    });
                }

            });
        }


        function GetCategoryByID(id) {
            $("#title").text("Details");

            var GetCategoryByIDUrl = '@Url.Action("GetCategoryByID", "Categories")';
           
            $.ajax({
                url: GetCategoryByIDUrl+ "/" + id,
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    console.log(data[0]);
                    $("#Id").val(data[0].Id);
                    $("#Name").val(data[0].Name);
                    isUpdatable = true;
                    $("#categoryModal").modal('show');
                },
                error: function (err) {
                    alert("Error: " + err.responseText);
                }
            });
        }

 

        //hàm Insert và Update
        function BtnSaveOnClick () {
            event.preventDefault();

            var CreateUrl = '@Url.Action("Create", "Categories")';
            var EditUrl = '@Url.Action("Edit", "Categories")';

            if (!isUpdatable) {
                var data = {
                    Name: $("#Name").val()
                }
            } else {
                var data = {
                    Id: $("#Id").val(),
                    Name: $("#Name").val()
                }
            }
            
           
            console.log(data);
            if (!isUpdatable) {
                $.ajax({
                    url: CreateUrl,
                    type: 'POST',
                    dataType: 'json',
                    data: data,
                    success: function (data) {
                        GetCategories();
                        $("#categoryModal").modal('hide');
                        clear();
                    },
                    error: function (err) {
                        alert("Error: " + err.responseText);
                    }
                })
            }
            else {
                $.ajax({
                    url: EditUrl,
                    type: 'POST',
                    dataType: 'json',
                    data: data,
                    success: function (data) {
                        GetCategories();
                        isUpdatable = false;
                        $("#categoryModal").modal('hide');
                        clear();
                    },
                    error: function (err) {
                        alert("Error: " + err.responseText);
                    }
                })
            }
        };

        function Delete(id) {
            var confirmDelete = confirm("Do you want to delete this Category ?");
            var DeleteUrl = '@Url.Action("Delete", "Categories")';
            if (confirmDelete) {
                $.ajax({
                    url: DeleteUrl + "/"+ id,
                    type: "POST",
                    dataType: 'json',
                    success: function (data) {
                        GetCategories();
                    },
                    error: function (err) {
                        alert("Error: " + err.responseText);
                    }
                });
            }
        }

        function BtnCreateNewOnClick() {
            $("#title").text("Create New");
            clear();
            isUpdatable = false;
        }

        // hàm đóng modal
        $("#btnClose").click(function () {
            clear();
        });

        // hàm reset giá trị về rỗng sau khi thực hiện Create hoặc Delete
        function clear() {

            $("#Id").val("");
            $("#Name").val("");
            
        }

    </script>
}